export enum Role {
  PROPERTY_SEEKER = 'PROPERTY_SEEKER',
  LANDLORD = 'LANDLORD',
  REAL_ESTATE_AGENT = 'REAL_ESTATE_AGENT',
  PROPERTY_MANAGER = 'PROPERTY_MANAGER',
  ADMIN = 'ADMIN',
}

export enum ListingStatus {
  DRAFT = 'DRAFT',
  PENDING_REVIEW = 'PENDING_REVIEW',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
  RENTED = 'RENTED',
}

export enum EnquiryStatus {
  PENDING = 'PENDING',
  REPLIED = 'REPLIED',
  CLOSED = 'CLOSED',
}

export enum ReportStatus {
  PENDING = 'PENDING',
  UNDER_REVIEW = 'UNDER_REVIEW',
  RESOLVED = 'RESOLVED',
  DISMISSED = 'DISMISSED',
}

export enum AuditAction {
  PROPERTY_APPROVED = 'PROPERTY_APPROVED',
  PROPERTY_REJECTED = 'PROPERTY_REJECTED',
  PROPERTY_STATUS_UPDATED = 'PROPERTY_STATUS_UPDATED',
  PROPERTY_DELETED = 'PROPERTY_DELETED',
  USER_SUSPENDED = 'USER_SUSPENDED',
  USER_ACTIVATED = 'USER_ACTIVATED',
  USER_ROLE_CHANGED = 'USER_ROLE_CHANGED',
  ENQUIRY_MODERATED = 'ENQUIRY_MODERATED',
}

export enum AuditTargetType {
  PROPERTY = 'PROPERTY',
  USER = 'USER',
  ENQUIRY = 'ENQUIRY',
  SYSTEM = 'SYSTEM',
}
